name: Flutter_Web_On_Demand

on:
  workflow_dispatch:
    inputs:
      printsomething:
        description: 'Framework version'
        required: true
        default: 'it-is-me'
      publish_artifacts:
        description: 'Publish artifacts'
        required: true
        default: 'true'

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}  

      - name: Set Flutter version
        run: 
          echo "printing ${{ github.event.inputs.printsomething }}"
